name: dotnet package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Install Chrome browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome-stable --headless --disable-gpu

      - name: Grant chromedriver permission
        run: sudo chmod +x ./SeleniumTCS/src/resources/driver

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Execute Selenium TCs
        run: dotnet test --no-restore --verbosity normal

      - name: Publish Selenium TCs results
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './SeleniumTCS/bin/Debug/net6.0/allure-results'
          keep_files: true
          user_name: arielforcode
          user_email: angelarielcamargomamani@gmail.com
          publish_branch: gh-pages

      - name: Test actions
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: './SeleniumTCS/bin/Debug/net6.0/allure-results'
          gh_pages: gh-pages
          allure_report: allure-report

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report 
